name: CI
on: push
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: 1.18
    - run: make build

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: 1.18
    - run: make test

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/build-push-action@v4.1.1

